eureka:
  instance:
   hostname: discovery-service
   port: 8761

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    register-with-eureka: false
    fetch-registry: false