eureka:
  instance:
   hostname: 192.168.0.5
   port: 8761

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    register-with-eureka: true
    fetch-registry: true