spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srast3/spring-kafka-microservice.git/
          search-paths:
            - "EmailServiceConfigProperties/{application}/{profile}"
#eureka:
#  instance:
#    hostname: config-server
#  client:
#    registryFetchIntervalSeconds: 1
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka/
